### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by jpopelka** [shaded-enmity/docker-network-capture#1]
```
$ pip3 install docker-network-capture
Collecting docker-network-capture
  Could not find a version that satisfies the requirement docker-network-capture (from versions: )
No matching distribution found for docker-network-capture
```

```
$ pip3 install docker-netowrk-capture
Collecting docker-netowrk-capture
  Downloading docker-netowrk-capture-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-avo39khn/docker-netowrk-capture/setup.py", line 5, in <module>
        version = open('VERSION').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```

Not sure you're aware of the project being called `docker-netowrk-capture` (not `docker-network-capture`) on PyPI ?

**Comment by shaded-enmity** [comment]
Fixed in 957798955120de433c3d056d9f8d2f2eb85ff33a

Thanks
